[package]
name = "rx_rs"
version = "0.1.1"
authors = ["rami3l <597974733.qq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.3.0"
regex = "1"
rustyline = "5"